ADD_SET_PRIORITY add set priority to workunit context menu
hpcc-systems/vscode-ecl pull request #374
Opened 2024-01-25 15:47 UTC by dehilsterlexis

2024-01-26 09:19 UTC, GordonSmith requested changes
Needs rebase as well

2024-01-26 09:19 UTC, GordonSmith commented on src/ecl/eclWatchTree.ts
> +import { SMCServiceBase } from "@hpcc-js/comms/src/services/wsdl/WsSMC/v1.27/WsSMC";
Should be:
```ts
import { SMCService} from "@hpcc-js/comms";
```

2024-01-26 14:09 UTC, GordonSmith approved these changes
Ready to pull - can you squash the two commits.

2024-01-26 16:25 UTC, dehilsterlexis commented
@GordonSmith need to test

2024-02-06 12:46 UTC, GordonSmith approved these changes

2024-02-06 12:46 UTC, merged