fix: add ask to delete to delete workunits
hpcc-systems/vscode-ecl pull request #380
Opened 2024-01-30 21:52 UTC by dehilsterlexis

#378

2024-02-06 12:52 UTC, GordonSmith requested changes

2024-02-06 12:52 UTC, GordonSmith commented on src/ecl/eclWatchTree.ts
> +		});
Indentation looks weird

2024-02-06 16:46 UTC, GordonSmith commented
@dehilsterlexis Looks like you merged trunk into this branch, instead of rebasing this branch onto upstream/trunk?

2024-02-06 20:17 UTC, dehilsterlexis commented
@GordonSmith I tried using the conflict resolution in github and it added that commit.

2024-02-07 09:19 UTC, GordonSmith commented
Yes that is what it looked like, I have straightened it out, but in the future just rebase to resolve any conflicts...

2024-02-07 09:20 UTC, GordonSmith approved these changes

2024-02-07 09:20 UTC, merged